version: '3.8'

services:
  app:
    build: .
    container_name: medibief_codeigniter_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"
    networks:
      - medibief-network
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: medibief_codeigniter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: codeigniter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - medibief-network

networks:
  medibief-network:
    driver: bridge

volumes:
  db_data: